# Generated by Django 4.2.9 on 2024-02-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cari_adi", models.CharField(max_length=255, verbose_name="Cari Adı")),
                (
                    "vergi_dairesi",
                    models.CharField(max_length=255, verbose_name="Vergi Dairesi"),
                ),
                (
                    "vergi_no",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Vergi No"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-Mail"
                    ),
                ),
                (
                    "adres",
                    models.TextField(blank=True, null=True, verbose_name="Adres"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
            ],
        ),
    ]
