# Generated by Django 4.2.9 on 2024-03-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cariler", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cari",
            options={"verbose_name": "Cari", "verbose_name_plural": "Cariler"},
        ),
    ]
