# Generated by Django 4.2.9 on 2024-03-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cariler", "0003_cari_caridurum"),
    ]

    operations = [
        migrations.RemoveField(model_name="cari", name="caridurum",),
        migrations.AddField(
            model_name="cari",
            name="borcAlacakDurumu",
            field=models.CharField(
                blank=True,
                choices=[("Borçlu", "Borçlu"), ("Alacaklı", "Alacaklı")],
                help_text="Borçlu veya Alacaklı Durum Seçiniz",
                max_length=10,
                null=True,
            ),
        ),
    ]
