# Generated by Django 4.2.9 on 2024-03-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cariler", "0004_remove_cari_caridurum_cari_borcalacakdurumu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cari", old_name="borcAlacakDurumu", new_name="cariDurum",
        ),
        migrations.AddField(
            model_name="cari",
            name="BorcAlacakMiktari",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Borç Alacak Miktarı",
            ),
        ),
    ]
