# Generated by Django 4.2.9 on 2024-03-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cariler", "0005_rename_borcalacakdurumu_cari_caridurum_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cari", name="BorcAlacakMiktari",),
        migrations.AddField(
            model_name="cari",
            name="Alacak",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="AlacakMiktarı"
            ),
        ),
        migrations.AddField(
            model_name="cari",
            name="Bakiye",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Bakiye"
            ),
        ),
        migrations.AddField(
            model_name="cari",
            name="Borc",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Borç Miktarı"
            ),
        ),
    ]
