# Generated by Django 4.2.9 on 2024-02-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("satislar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="satis",
            name="aciklama",
            field=models.CharField(default=1, max_length=255, verbose_name="Açıklama"),
            preserve_default=False,
        ),
    ]
