# Generated by Django 4.2.9 on 2024-02-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("satislar", "0002_satis_aciklama"),
    ]

    operations = [
        migrations.AlterField(
            model_name="satis",
            name="aciklama",
            field=models.CharField(
                default="Nakit Tahsilat", max_length=255, verbose_name="Açıklama"
            ),
        ),
    ]
