# Generated by Django 4.2.9 on 2024-03-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("satislar", "0003_alter_satis_aciklama"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="satis",
            options={"verbose_name": "Satışlar", "verbose_name_plural": "Satışlar"},
        ),
        migrations.AlterField(
            model_name="satis",
            name="aciklama",
            field=models.CharField(
                default="Nakit Tahsilat", max_length=2550, verbose_name="Açıklama"
            ),
        ),
    ]
