# Generated by Django 4.2.9 on 2024-03-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cariler", "0002_alter_cari_options"),
        ("sakiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="sakizmakinesi", name="marka",),
        migrations.AddField(
            model_name="sakizmakinesi",
            name="cari",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cariler.cari",
            ),
        ),
    ]
