# Generated by Django 4.2.9 on 2024-03-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sakiz", "0002_remove_sakizmakinesi_marka_sakizmakinesi_cari"),
    ]

    operations = [
        migrations.RemoveField(model_name="sakizmakinesi", name="model",),
        migrations.AddField(
            model_name="sakizmakinesi",
            name="ciroTL",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="sakizmakinesi",
            name="ciroToplam",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
