# Generated by Django 4.2.9 on 2024-03-04 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sakiz", "0003_remove_sakizmakinesi_model_sakizmakinesi_cirotl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sakizmakinesi",
            name="aciklama",
            field=models.CharField(default="", max_length=255, verbose_name="Açıklama"),
        ),
        migrations.AddField(
            model_name="sakizmakinesi",
            name="acilanSakiz",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Açılan sakız miktarını giriniz.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sakizmakinesi",
            name="acilanTop",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Açılan top miktarını giriniz.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sakizmakinesi",
            name="bolge",
            field=models.CharField(default="", max_length=255, verbose_name="Bölge"),
        ),
        migrations.AddField(
            model_name="sakizmakinesi",
            name="ciroBayi",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Kilogram Cinsinden Bayi Cirosu",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sakizmakinesi",
            name="ciroBayiTL",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="TL Cinsinden Bayi Cirosu",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sakizmakinesi",
            name="ciroBuldukTL",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="TL Cinsinden Bulduk Cirosu",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sakizmakinesi",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="sakizmakinesi",
            name="makineNo",
            field=models.CharField(
                default="", max_length=255, verbose_name="Makine No"
            ),
        ),
        migrations.AddField(
            model_name="sakizmakinesi",
            name="verilenOyuncak",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Verilen oyuncak miktarını giriniz.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sakizmakinesi",
            name="verilenTL",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Verilen ciroyu TL cinsinden giriniz.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sakizmakinesi",
            name="ciroTL",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Toplam ciroya karşılık gelen TL miktarı.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sakizmakinesi",
            name="ciroToplam",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Toplam ciroyu kilogram cinsinden giriniz.",
                max_digits=10,
            ),
        ),
    ]
