# Generated by Django 4.2.9 on 2024-03-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sakiz", "0004_sakizmakinesi_aciklama_sakizmakinesi_acilansakiz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sakizmakinesi",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
    ]
