# Generated by Django 4.2.9 on 2024-03-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sakiz", "0006_alter_sakizmakinesi_aciklama_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="sakizmakinesi", name="bolge",),
        migrations.AlterField(
            model_name="sakizmakinesi",
            name="acilanSakiz",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Açılan sakız miktarını giriniz.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sakizmakinesi",
            name="ciroToplam",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Toplam ciroyu kilogram cinsinden giriniz.",
                max_digits=10,
            ),
        ),
    ]
