# Generated by Django 4.2.9 on 2024-03-06 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cariler", "0005_rename_borcalacakdurumu_cari_caridurum_and_more"),
        ("sakiz", "0008_remove_sakizmakinesi_cari"),
    ]

    operations = [
        migrations.AddField(
            model_name="sakizmakinesi",
            name="cari",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cariler.cari",
            ),
        ),
    ]
