# Generated by Django 4.2.9 on 2024-03-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cariler", "0006_remove_cari_borcalacakmiktari_cari_alacak_and_more"),
        ("sakiz", "0009_sakizmakinesi_cari"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sakizmakinesi",
            name="cari",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cariler.cari"
            ),
        ),
    ]
