# Generated by Django 4.2.9 on 2024-03-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sakiz", "0010_alter_sakizmakinesi_cari"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sakizmakinesi", options={"ordering": ["-created_date"]},
        ),
    ]
