# Generated by Django 4.2.9 on 2024-03-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("satinalma", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="satinalma",
            name="cari_adi",
            field=models.CharField(max_length=255, verbose_name="Cari Adı"),
        ),
    ]
